import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { Inter } from 'next/font/google';
import { ConnectButton } from '@rainbow-me/rainbowkit';

import './globals.css';
import '@rainbow-me/rainbowkit/styles.css';

import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ETH Bundle',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = headers().get('cookie');

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div
            style={{
              display: 'flex',
              justifyContent: 'flex-end',
              padding: 12,
            }}
          >
            <ConnectButton />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
